#!/usr/bin/env zsh

case "$1" {
  "C-c") { echo -n "$2" | xsel -i       } ;;
  "C-d") { trash-put "$2"               } ;;
  "C-g") { gimp "$2"                    } ;;
  "C-i") { exiv2 pr -q -p s "$2" | less } ;;
  "C-r") { mogrify -rotate +90 "$2"     } ;;
  "C-w") { hsetroot -fill "$2"          } ;;
}
