#!/bin/sh

PANEL_HEIGHT=15
FONT_FAMILY='Source Code Pro'
FONT_SIZE='7'
WIDTH=1366

[ -e "$BSPWM_PANEL_FIFO" ] && rm "$BSPWM_PANEL_FIFO"
mkfifo "$BSPWM_PANEL_FIFO"

# Feed the fifo
bspc control --subscribe > "$BSPWM_PANEL_FIFO" &

cat "$BSPWM_PANEL_FIFO" | \
  $XDG_CONFIG_HOME/bspwm/panel/panel_dzen2 -f "$FONT_FAMILY" -s "$FONT_SIZE" | \
  dzen2 -h $PANEL_HEIGHT -w "$(( $WIDTH / 2 ))" -y 768 -ta l -fn "${FONT_FAMILY}:size=${FONT_SIZE}" -fg "#ddccbb" -bg "#181512"

wait
