#!/bin/sh

NORMIFS=$IFS
FIELDIFS=':'
PADDING=' '

shift $((OPTIND - 1))

while read -r line ; do
    case $line in
        W*)
            # bspwm internal state
            wm_infos="$PADDING"
            IFS=$FIELDIFS
            set -- ${line#?}
            while [ $# -gt 0 ] ; do
                item=$1
                case $item in
                    [OoFfUu]*)
                        # desktops
                        name=${item#?}
                        case $item in
                            O*)
                                # focused occupied desktop
                                FG=#FFEEDD
                                BG=#544C45
                                ;;
                            F*)
                                # focused free desktop
                                FG=#FFEEDD
                                BG=#544C45
                                ;;
                            U*)
                                # focused urgent desktop
                                FG=#FFEEDD
                                BG=#544C45
                                ;;
                            o*)
                                # occupied desktop
                                FG=#DDCCBB
                                BG=#2B2825
                                ;;
                            f*)
                                # free desktop
                                FG=#DDCCBB
                                BG=#2B2825
                                ;;
                            u*)
                                # urgent desktop
                                FG=#DDCCBB
                                BG=#DDCCBB
                                ;;
                        esac
                        wm_infos="${wm_infos}^fg(#000)^r(1x15)^fg(#444)^r(1x15)^fg(${FG})^bg(${BG})^ca(1, bspc desktop -f ${name})^ca(2, bspc window -d ${name})${PADDING}${name}${PADDING}^ca()^ca()"
                        ;;
                    L*)
                        # layout
                        layout=$(printf "%s" "${item#?}" | sed 's/^\(.\).*/\U\1/')
                        wm_infos="${wm_infos}^fg()^bg()^ca(1, bspc desktop -l next)^fg(#000)^r(1x15)^fg(#888)^r(1x15)^bg(#64553C)^fg(#DDCCBB) $layout ^fg(#000)^r(1x15)^fg(#444)^r(1x15)^bg()${PADDING}^ca()"
                        ;;
                esac
                shift
            done
            IFS=$NORMIFS
            ;;
    esac
    printf "%s\n" "$wm_infos"
done
