#!/bin/sh

export _XINIT_WM="${@-"openbox"}"

eval `dbus-launch --sh-syntax --exit-with-session`

setxkbmap -layout br
setxkbmap -option terminate:ctrl_alt_bksp
setxkbmap -option compose:rwin
xset r rate 340 40
xset b off
xset s off
xset -dpms
xsetroot -cursor_name left_ptr
xrdb -load "$HOME/etc/X11/Xresources"
xrdb -merge "$HOME/etc/X11/colortheme"
xmodmap "$HOME/etc/X11/xmodmaprc" &

autocutsel -fork &
unclutter -root -idle 2 &
nitrogen --restore &

if [ "$_XINIT_WM" == "openbox" ]; then
  tint2 &
  compton -b &
fi

$_XINIT_WM
