#!/usr/bin/env sh

export _XINIT_WM="${@-"bspwm"}"
eval `dbus-launch --sh-syntax --exit-with-session`

autostart() {
  while ! killall -0 "$_XINIT_WM"; do sleep 1; done
  nitrogen --restore &
  xcmenu --daemon &
  unclutter -root -idle 2 &
  xmodmap "$XDG_CONFIG_HOME/X11/xmodmaprc" &
  #redshift -l 21:51 -m randr &
  #compton -b
}

autokill() {
  #killall redshift
  killall xcmenu
  killall unclutter
}

setxkbmap -layout br
xset r rate 340 40
xsetroot -cursor_name left_ptr
xrdb -load "$XDG_CONFIG_HOME/X11/Xresources"

autostart &
$_XINIT_WM &>/dev/null
autokill; sleep 1
