#!/bin/sh

export _XINIT_WM="${@-"openbox"}"

# X11 stuff {{{
# Keyboard layout
setxkbmap br
# Kill X with Ctrl-Alt-Backspace
setxkbmap -option terminate:ctrl_alt_bksp
# Key repeat rate
xset r rate 250 50
# Root window doesn't have a 'x' as cursor
xsetroot -cursor_name left_ptr
# Load Xresources
xrdb -load $XDG_CONFIG_HOME/X11/Xresources
# Xmodmap
xmodmap $XDG_CONFIG_HOME/X11/xmodmaprc
# }}}

# Apps {{{
start() {
  # Set wallpaper
  nitrogen --restore &
  # Hide the pointer
  unclutter -root -idle 1 &
  # Composite
  compton &
  # Tint2
  tint2 &
  # Dzen bar
  dzenstatus &
} # }}}

start; $_XINIT_WM
