set runtimepath=~/etc/vim,~/etc/vim/bundle/vundle,$VIMRUNTIME

" Vundle {{{
set nocompatible              " be iMproved
filetype off                  " required!

call vundle#begin("~/etc/vim/bundle")

" let Vundle manage Vundle
" required!
Plugin 'gmarik/vundle'

" My bundles here:
"
" original repos on GitHub
"Plugin 'Shougo/neocomplcache.vim'
"Plugin 'bling/vim-airline'
Plugin 'itchyny/lightline.vim'
Plugin 'scrooloose/syntastic'
"Plugin 'Valloric/YouCompleteMe'
Plugin 'kien/ctrlp.vim'
"Plugin 'mattn/emmet-vim'
Plugin 'w0ng/vim-hybrid'

call vundle#end()

filetype plugin indent on     " required!
syntax on
" }}}
" Vim options {{{
set t_Co=256
let g:hybrid_use_Xresources=1
colorscheme hybrid

if $TERM == 'linux'
  set t_Co=8
  set nolist
endif

if has('gui_running')
  set guifont=Meslo\ LG\ M\ for\ Powerline\ 8

  set guicursor+=a:blinkon0
  set guioptions-=T
  set guioptions-=l
  set guioptions-=L
  set guioptions-=r
  set guioptions-=R
  set guioptions-=m
endif

set background=dark
colorscheme hybrid

set autochdir
set autoindent
set autoread
set backspace=start,indent,eol
set confirm
set clipboard+=unnamed
" set cmdheight=2
set cursorline
set expandtab
set foldcolumn=0
set foldenable
set foldlevel=0
set foldmethod=marker
set hlsearch
set ignorecase
set incsearch
set laststatus=2
set lazyredraw
set list
set listchars=tab:>-,trail:·,eol:<,precedes:«,extends:»
set magic
set modeline
set modelines=2
set mouse=a
set nobackup
set noerrorbells
set norelativenumber
set noshowmode
set noswapfile
set nowrap
set nowritebackup
set number
" set paste
set preserveindent
set scrolloff=4
set sidescroll=4
set shiftwidth=2
set shortmess=aIoOT
set showbreak=↪
set showcmd
set softtabstop=2
set smartcase
set smarttab
set splitbelow
set tabstop=2
set title
set ttyfast
"set undofile
"set undodir=~/var/vim
set virtualedit=all
set wildmenu
set wildmode=list:longest,full
set wildignore=*.swp,*.bak,*~,blib,*.o,*.png,*.jpe?g,.git,.svn,*.so,.hg
" }}}
" Autocmds {{{
if has("autocmd")
  " always jump to the last cursor position
  autocmd BufReadPost * if line("'\"")>0 && line("'\"")<=line("$")|exe "normal g`\""|endif
endif
" }}}
" Sources {{{
source ~/etc/vim/user/plugins.vim
source ~/etc/vim/user/keybindings.vim
" }}}
