#!/bin/sh

#      ___           ___                         ___           ___
#     /  /\         /  /\          ___          /  /\         /  /\
#    /  /::\       /  /::\        /  /\        /  /:/_       /  /::|
#   /  /:/\:\     /__/:/\:\      /  /::\      /  /:/ /\     /  /:|:|
#  /  /::\ \:\   _\_ \:\ \:\    /  /:/\:\    /  /:/ /:/_   /  /:/|:|__
# /__/:/\:\_\:| /__/\ \:\ \:\  /  /::\ \:\  /__/:/ /:/ /\ /__/:/_|::::\
# \  \:\ \:\/:/ \  \:\ \:\_\/ /__/:/\:\_\:\ \  \:\/:/ /:/ \__\/  /~~/:/
#  \  \:\_\::/   \  \:\_\:\   \__\/  \:\/:/  \  \::/ /:/        /  /:/
#   \  \:\/:/     \  \:\/:/        \  \::/    \  \:\/:/        /  /:/
#    \__\::/       \  \::/          \__\/      \  \::/        /__/:/
#        ~~         \__\/                       \__\/         \__\/
#
#                       ~/.config/bspwm/autostart
#                 Author: suare (http://github.com/suare)

# Initiate workspaces
FIRST_DESK=1
REMAINING_DESKS='2 3 4 5 6'

bspc desktop Desktop01 -n $FIRST_DESK
bspc monitor -a $REMAINING_DESKS

# Rules
bspc rule -a qtermite --floating
bspc rule -a chromium -d 2 --follow
bspc rule -a Gimp -d 4 --floating

# Bspwm own options
bspc config adaptive_raise      true
bspc config auto_cancel         true
bspc config focus_follows_pointer false
bspc config split_ratio         0.50

# Padding for statusbar
bspc monitor -p 14 0 0 0

# Decoration
bspc config border_width        5
bspc config window_gap          3
bspc config borderless_monocle  true
bspc config gapless_monocle     true

# Colors
bspc config focused_border_color        "#262935"
bspc config active_border_color         "#5C5955"
bspc config normal_border_color         "#202224"
bspc config focused_locked_border_color "#D64C8A"
bspc config active_locked_border_color  "#A363B2"
bspc config normal_locked_border_color  "#4F3755"
bspc config urgent_border_color         "#00C7D8"
bspc config presel_border_color         "#505052"
