#!/bin/bash

FIRST_DESK=1
REMAINING_DESKS='2 3 4 5'

bspc rename Desktop01 $FIRST_DESK
bspc add $REMAINING_DESKS

bspc rule Gimp 4 floating follow
bspc rule Inkscape 4 floating follow
bspc rule Skype 3 floating
bspc rule Nitrogen 5 floating

bspc set border_width 8
bspc set window_gap   2
bspc set top_padding  14
bspc set split_ratio  0.50

bspc set borderless_monocle    true
bspc set gapless_monocle       true
bspc set focus_follows_pointer false
bspc set adaptative_raise      true
bspc set apply_shadow_property true
bspc set focus_by_distance     true

bspc set focused_border_color "#455055"
bspc set normal_border_color  "#202020"

if [ -e "$BSPWM_BACKUP" ] ; then
bspc restore "$BSPWM_BACKUP"
    rm "$BSPWM_BACKUP"
else
bspc adopt_orphans
fi

if [ -e "$BSPWM_LAYOUT" ] ; then
    bspc restore_layout "$BSPWM_LAYOUT"
    rm "$BSPWM_LAYOUT"
else
    bspc adopt_orphans
fi

if [ -e "$BSPWM_HISTORY" ] ; then
    bspc restore_history "$BSPWM_HISTORY"
    rm "$BSPWM_HISTORY"
fi

updatethm
compton --shadow-exclude '_COMPTON_SHADOW:32c = 0' -bc -t -8 -l -9 -r 6 -o 0.7 -e 0.8

killall sxhkd
sxhkd
