#!/bin/sh

## Initiate workspaces:
FIRST_DESK=1
REMAINING_DESKS='2 3 4 5 6'

bspc rename Desktop01 $FIRST_DESK
bspc add $REMAINING_DESKS

bspc set top_padding  15

## Rules:
bspc rule sxiv floating
bspc rule chromium 2 follow
bspc rule Gimp 4 floating

## Settings:
#+ focus
bspc set history_aware_focus true
bspc set focus_by_distance   false

#+ splitting
bspc set split_ratio         0.50

#+ decoration
bspc set border_width        5
bspc set window_gap          2
bspc set borderless_monocle  true
bspc set gapless_monocle     true

#+ colors
bspc set focused_border_color        "#262935"
bspc set active_border_color         "#5C5955"
bspc set normal_border_color         "#202224"
bspc set focused_locked_border_color "#D64C8A"
bspc set active_locked_border_color  "#A363B2"
bspc set normal_locked_border_color  "#4F3755"
bspc set urgent_border_color         "#00C7D8"
bspc set presel_border_color         "#505052"
