#!/usr/bin/env zsh

# Workspaces names {{{
bspc monitor --reset-desktops b s p w m
# }}}
# Options {{{
                bspc config border_width 1
                  bspc config window_gap 4
                 bspc config split_ratio 0.5
              bspc config bottom_padding 18
                 bspc config top_padding 0
                bspc config left_padding 0
               bspc config right_padding 0
              bspc config auto_alternate "true"
                 bspc config auto_cancel "true"
         bspc config history_aware_focus "true"
          bspc config borderless_monocle "true"
             bspc config gapless_monocle "true"
       bspc config focus_follows_pointer "true"
     bspc config pointer_follows_monitor "false"
         bspc config apply_floating_atom "true"
           bspc config ignore_ewmh_focus "false"
     bspc config remove_disabled_monitor "true"
# }}}
# Colors {{{
        bspc config focused_border_color "#9F7050"
         bspc config normal_border_color "#080808"
         bspc config presel_border_color "#CCBBBB"
 bspc config focused_locked_border_color "#383532"
  bspc config normal_locked_border_color "#20171D"
         bspc config urgent_border_color "#FAFAC0"
# }}}
# Rules {{{
bspc rule --add gimp floating=on center=on follow=off desktop=^4
bspc rule --add firefox floating=off center=off follow=on desktop=^2
bspc rule --add mplayer floating=on center=on follow=on desktop=^3
bspc rule --add mpv floating=on center=on follow=on desktop=^3
bspc rule --add nitrogen floating=on center=on follow=off desktop=^3
bspc rule --add deluge floating=on center=off follow=off desktop=^3
bspc rule --add xfontsel floating=on center=on follow=on desktop=^4
bspc rule --add lxappearance floating=on center=off follow=on desktop=^3
bspc rule --add feh floating=on center=on follow=on desktop=^4
bspc rule --add sxiv floating=on center=on follow=on desktop=^4
bspc rule --add orage floating=on center=off follow=on
bspc rule --add leafpad floating=on center=off follow=on
bspc rule --add zathura floating=off center=off follow=on desktop=^4
bspc rule --add pavucontrol floating=on center=on follow=on desktop=^4
# }}}
# Startup {{{
panel &
statusbar &
sxhkd -c "${XDG_CONFIG_HOME}/bspwm/keybindings" &
# }}}
