#!/bin/sh

# Workspaces names {{{
bspc monitor -d I II III IV V VI VII VIII IX X
# }}}
# Rules {{{
bspc rule -a gimp         floating=on   center=on  follow=off desktop=IV
bspc rule -a Firefox      floating=off  center=off follow=on  desktop=II
bspc rule -a mplayer      floating=on   center=on  follow=on  desktop=III
bspc rule -a mpv          floating=on   center=on  follow=on  desktop=III
bspc rule -a nitrogen     floating=on   center=on  follow=off desktop=III
bspc rule -a deluge       floating=on   center=off follow=off desktop=III
bspc rule -a xfontsel     floating=on   center=on  follow=on  desktop=IV
bspc rule -a lxappearance floating=on   center=off follow=on  desktop=III
bspc rule -a rox          floating=on   center=off follow=off desktop=III
# }}}
# Options {{{
bspc config border_width                1
bspc config window_gap                  6
bspc config split_ratio                 0.5
bspc config bottom_padding              15
bspc config top_padding                 0
bspc config auto_cancel                 true
bspc config history_aware_focus         true
bspc config borderless_monocle          true
bspc config gapless_monocle             true
bspc config focus_follows_pointer       true
bspc config apply_floating_atom         true
# }}}
# Colors {{{
bspc config focused_border_color        "#B16E43"
bspc config active_border_color         "#282522"
bspc config normal_border_color         "#181512"
bspc config presel_border_color         "#383532"
bspc config focused_locked_border_color "#BEC17E"
bspc config active_locked_border_color  "#484542"
bspc config normal_locked_border_color  "#282522"
bspc config urgent_border_color         "#FAFAC0"
# }}}
