#!/bin/bash
# Modified from HerbstluftWM's panel.sh

#======~===~==============~===========~==
# COLORS
#==~==========~=========~=============~~=

# Getting colors from `xrdb -query`
if [[ $(uname) == 'FreeBSD' ]]; then
  xrdb=( $(xrdb -query | grep "color[0-9]*:" | sort | cut -f 2-) )
else
  xrdb=( $(xrdb -query | grep -P "color[0-9]*:" | sort | cut -f 2-) )
fi

declare -A color

index=0

for name in black brightgreen brightyellow brightblue brightmagenta brightcyan brightwhite red green yellow blue magenta cyan white grey brightred; do
  color[${name}]=${xrdb[$index]}
  ((index++))
done

#bgcolor='#1f1b18'
bgcolor='#0F0F0F'

#======~===~==============~===========~==
# GEOMETRY
#==~==========~=========~=============~~=
x=0
y=768
width=1366
height=15

#font="-windows-montecarlo-medium-r-normal--11-110-72-72-c-60-microsoft-cp1252"
#bold="-windows-montecarlo-medium-r-normal--11-110-72-72-c-60-microsoft-cp1252"

font="-artwiz-cure-medium-r-normal--11-110-75-75-p-90-iso8859-1"
bold="-artwiz-cure-medium-r-normal--11-110-75-75-p-90-iso8859-1"

# Using a different font to calculate text width (`textwidth` doesn't work with truetype fonts)
# Neep Semicondensed 11 has the same char width as Pragmata 7pt
calcfont="-jmk-neep-medium-r-semicondensed--11-100-75-75-c-50-iso8859-9"

#======~===~==============~===========~==
# ICONS
#==~==========~=========~=============~~=
iconpath=/home/luizf/.config/icons

function icon() {
   echo -n "^bg(#C7F09F) ^fg(#000000)^i(${iconpath}/${1}.xbm)^fg()^bg(#C7F09F) ^bg(#151515)"
}

#======~===~==============~===========~==
# CPU
#==~==========~=========~=============~~=
function temperature() {
	temp=$(sensors | grep -P "Core 0" | cut -b 18-25)
	echo -n $(icon temp yellow) ${temp}
}

function cpu() {
cpu=$(cut -d " " -f 1-3 /proc/loadavg)
  echo -n $(icon cpu cyan) ${cpu}
}

#======~===~==============~===========~==
# BATTERY
#==~==========~=========~=============~~=
function battery() {
  bat="$(acpi | awk '{ print $4 }' | sed s/","//g | sed s/"%"//g)"
  echo -n "$(icon ac1 brightred) ${bat}^fg(#606060)%"
}

#======~===~==============~===========~==
# MPD
#==~==========~=========~=============~~=
function m() {
  mpc -f %${1}% current | sed 's/ä/ae/g' | sed 's/ö/oe/g' | sed 's/ü/ue/g'
}

function nowplaying() {
echo -n "$(icon note1 magenta) $(m title) ^fg(#505050)by^fg() $(m artist) ^fg(#505050)on^fg() $(m album)"
}

function uniq_linebuffered() {
	awk '$0 != l { print ; l=$0 ; fflush(); }' "$@"
}

{
	tail -f ~/.config/stumpwm/stumpwm.log &
	tail -f ${irssilog} &
   mpc idleloop player &
	while true ; do
		date +'date ^fg() %H:%M^fg(#707070), %Y-%m-^fg()%d'
		sleep 1 || break
	done | (uniq_linebuffered)  &
	while true ; do
		echo "vol $(amixer get PCM | tail -1 | sed 's/.*\[\([0-9]*%\)\].*/\1/')"
		sleep 1 || break
	done | (uniq_linebuffered) &
} 2> /dev/null | {
	while :; do

		ws=$(~/bin/dzen_groups.sh)
		echo -n " ^fn($bold)$ws^fn()"

		right=""
		for func in battery temperature cpu nowplaying; do
			right="$right $(${func})"
		done

		right="$right $(icon volume_on blue) $volume"

		# Date
		right="$right $(icon clock1 green)^fn($bold)$date^fn()"
		right_text_only=$(echo -n "$right"|sed 's.\^[^(]*([^)]*)..g')

		# get width of right aligned text.. and add some space..
		width=$(textwidth $calcfont "$right_text_only         ")
		echo -n "^p(_RIGHT)^p(-$width)$right"
		echo

		# wait for next event
		read line || break
		cmd=( $line )

		# find out event origin
		case "${cmd[0]}" in
			date)
				date="${cmd[@]:1}" ;;
			vol)
				volume="${cmd[@]:1}" ;;
		esac
	done
} 2> /dev/null | dzen2 -w $width -x $x -y $y -fn "$font" -h $height -ta l -bg "$bgcolor" -fg '#909090'
