#!/bin/bash

FIRST_DESK=1
REMAINING_DESKS='2 3 4 5'

bspc rename Desktop01 $FIRST_DESK
bspc add $REMAINING_DESKS

bspc rule Gimp 4 floating follow
bspc rule Inkscape 4 floating follow
bspc rule Skype 5 floating follow
bspc rule Nitrogen 5 floating

bspc set border_width  8
bspc set window_gap    6
# bspc set top_padding   24
bspc set split_ratio   0.52

bspc set borderless_monocle    true
bspc set gapless_monocle       false
bspc set focus_follows_pointer false
bspc set adaptative_raise      false
bspc set apply_shadow_property true

bspc set focused_border_color "#323538"
bspc set normal_border_color "#161820"

if [ -e "$BSPWM_BACKUP" ] ; then
bspc restore "$BSPWM_BACKUP"
    rm "$BSPWM_BACKUP"
else
bspc adopt_orphans
fi

updatethm
# compton --shadow-exclude '_COMPTON_SHADOW:32c = 0' -bc -t -8 -l -9 -r 6 -o 0.7 -e 0.8
