# Autoload stuff
autoload -U compinit && compinit

# Source zsh files out there
for r in ${HOME}/dots/zsh/*.zsh; do
  if [[ $DEBUG > 0 ]]; then
    echo "zsh: sourcing $r"
  fi
  source $r
done

# Startup message
# echo -e "I'm \e[1;31m$(whoami) \e[mat \e[1;33m$(uname -n)\n"