#!/usr/bin/env zsh

#+ Startup {{{
hc() { CMD=($CMD , $@) }
hc emit_hook reload
hc keyunbind --all
hc mouseunbind --all
hc unrule -F
hc unsetenv HCT
# }}}

#+ Default applications {{{
LAUNCHER="dmenu_run"
TERM="terminal"
# }}}

#+ Keyboard {{{
resizestep=0.01
Mod="Mod4"

hc keybind $Mod-Control-space   split explode
hc keybind $Mod-space           cycle_layout 1
hc keybind $Mod-BackSpace       cycle_monitor
hc keybind $Mod-Tab             cycle_all +1
hc keybind $Mod-Shift-Tab       cycle_all -1
hc keybind $Mod-Return          spawn "$TERM"
hc keybind $Mod-period          use_index +1 --skip-visible
hc keybind $Mod-comma           use_index -1 --skip-visible
hc keybind $Mod-Shift-b         spawn "$BROWSER"
hc keybind $Mod-c               cycle
hc keybind $Mod-d               remove
hc keybind $Mod-f               floating toggle
hc keybind $Mod-Shift-f         fullscreen toggle
hc keybind $Mod-Shift-g         spawn "gcolor2"
hc keybind $Mod-h               focus left
hc keybind $Mod-j               focus down
hc keybind $Mod-k               focus up
hc keybind $Mod-l               focus right
hc keybind $Mod-Shift-h         shift left
hc keybind $Mod-Shift-j         shift down
hc keybind $Mod-Shift-k         shift up
hc keybind $Mod-Shift-l         shift right
hc keybind $Mod-Control-h       resize left  +"$resizestep"
hc keybind $Mod-Control-j       resize down  +"$resizestep"
hc keybind $Mod-Control-k       resize up    +"$resizestep"
hc keybind $Mod-Control-l       resize right +"$resizestep"
hc keybind $Mod-i               pseudotile toggle
hc keybind $Mod-q               close
hc keybind $Mod-p               spawn "$LAUNCHER"
hc keybind $Mod-Shift-r         reload
hc keybind $Mod-minus           split bottom 0.5
hc keybind $Mod-equal           split right 0.5
hc keybind $Mod-Shift-q         quit
hc keybind $Mod-u               jumpto urgent

hc mousebind $Mod-Button1       move
hc mousebind $Mod-Button2       zoom
hc mousebind $Mod-Button3       resize
# }}}

#+ Tags {{{
tag_names=( {1..5} )
tag_keys=( {1..5} )

hc rename default "${tag_names[1]}"
for ((i=1; i<$((${tag_keys[-1]}+1)); i++)); do
  [[ $i -gt ${tag_keys[1]} ]] && hc add ${tag_names[$i]}
  hc keybind Mod4-${i[-1]} use ${tag_names[$i]}
  hc keybind Mod4-Shift-${i[-1]} move ${tag_names[$i]}
done
# }}}

#+ Rules {{{
hc rule focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK)' manage=off
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(FULLSCREEN|FS)' fullscreen=on
# }}}

#+ Options {{{
hc set focus_follows_mouse        0
hc set raise_on_focus             0
hc set raise_on_click             1

hc set frame_border_width         1
hc set window_border_width        3
hc set window_border_inner_width  1
hc set always_show_frame          1
hc set frame_bg_transparent       1
hc set frame_transparent_width    0
hc set frame_gap                  2
hc set window_gap                 -2
hc set frame_padding              2
hc set smart_window_surroundings  0
hc set smart_frame_surroundings   0
hc set mouse_recenter_gap         0

hc set frame_border_active_color  "#020202"
hc set frame_border_normal_color  "#080808"
hc set frame_bg_normal_color      "#100D0A"
hc set frame_bg_active_color      "#181512"
hc set window_border_normal_color "#25221F"
hc set window_border_active_color "#585250"
# }}}

#+ Unknown {{{
hc unlock
hc set tree_style "╾│ ├└╼─┐"
# }}}

herbstclient chain ${CMD} &
