#!/bin/bash

# this is a simple config for herbstluftwm

function hc() {
    herbstclient "$@"
}

hc emit_hook reload

# tags
TAG_NAMES=( {1..5} )




# colors
hc set frame_border_active_color '#101010'
hc set frame_border_normal_color '#101010'
hc set frame_bg_normal_color '#151515'
hc set frame_bg_active_color '#101010'
hc set frame_border_width 1
hc set window_border_width 4
hc set window_border_inner_width 1
hc set window_border_normal_color '#1c1c1c'
hc set window_border_active_color '#607B8B'
hc set always_show_frame 1
hc set frame_gap 4
# add overlapping window borders
hc set window_gap -2
hc set frame_padding 2
hc set smart_window_surroundings 0
hc set smart_frame_surroundings 1
hc set mouse_recenter_gap 0

# remove all existing keybindings
hc keyunbind --all
hc mouseunbind --all

# keybindings
Mod=Mod4
hc keybind $Mod-Shift-r   reload
hc keybind $Mod-Control-q spawn systemctl poweroff
hc keybind $Mod-Control-r spawn systemctl reboot
hc keybind $Mod-q         close
hc keybind $Mod-Shift-q   spawn sh $HOME/.config/herbstluftwm/hc_close_remove
hc keybind $Mod-b         spawn luakit
hc keybind $Mod-Return    spawn urxvtc
hc keybind Menu           spawn dmenu_run -fn "-schumacher-clean-medium-r-normal--10-100-75-75-c-50-iso646.1991-irv" -p "Run:" -nb "#151515" -nf "#807777" -sb "#607B8B" -sf "#DDDDDD" 
hc keybind Print          spawn scrot /mnt/data/%d-%m-%Y_%H:%M.png 

# cycle through tags
hc keybind $Mod-period use_index +1 --skip-visible
hc keybind $Mod-comma  use_index -1 --skip-visible
hc keybind $Mod-Right  use_index +1 --skip-visible
hc keybind $Mod-Left   use_index -1 --skip-visible


# layouting
hc keybind $Mod-d       remove
hc keybind $Mod-space   cycle_layout 1
hc keybind $Mod-Shift-s split vertical 0.5
hc keybind $Mod-s       split horizontal 0.5
hc keybind $Mod-f       floating toggle
hc keybind $Mod-F10     fullscreen toggle
hc keybind $Mod-p       pseudotile toggle

# resizing
RESIZESTEP=0.01

hc keybind $Mod-Shift-h resize left  +$RESIZESTEP
hc keybind $Mod-Shift-j resize down  +$RESIZESTEP
hc keybind $Mod-Shift-k resize up    +$RESIZESTEP
hc keybind $Mod-Shift-l resize right +$RESIZESTEP

# mouse
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 resize
hc mousebind $Mod-Button3 zoom

# focus
hc keybind $Mod-BackSpace cycle_monitor
hc keybind $Mod-Tab       cycle_all +1
hc keybind $Mod-Shift-Tab cycle_all -1
hc keybind $Mod-c         cycle
hc keybind $Mod-h         focus left
hc keybind $Mod-j         focus down
hc keybind $Mod-k         focus up
hc keybind $Mod-l         focus right
hc keybind $Mod-i         jumpto urgent
hc keybind $Mod-Control-h shift left
hc keybind $Mod-Control-j shift down
hc keybind $Mod-Control-k shift up
hc keybind $Mod-Control-l shift right

# media keys
hc keybind XF86AudioNext        spawn mpc next
hc keybind XF86AudioPrev        spawn mpc prev
hc keybind XF86AudioPlay        spawn mpc toggle
hc keybind XF86AudioStop        spawn mpc stop
hc keybind XF86AudioRaiseVolume spawn amixer -q sset PCM 1%+ unmute
hc keybind XF86AudioLowerVolume spawn amixer -q sset PCM 1%- unmute
hc keybind XF86AudioMute        spawn amixer -q sset Master toggle

hc keybind XF86WWW        spawn luakit
hc keybind XF86Calculator spawn xcalc
hc keybind XF86AudioMedia spawn urxvtc -e ncmpcpp
hc keybind XF86Mail       spawn urxvtc -e mutt 
hc keybind XF86Explorer   spawn urxvtc -e ranger 
hc keybind XF86News       spawn urxvtc -e newsbeuter 
hc keybind XF86PowerOff   spawn systemctl poweroff

TAG_KEYS=( {1..9} 0 )  
hc rename default "${TAG_NAMES[0]}" || true
for i in ${!TAG_NAMES[@]} ; do
    hc add "${TAG_NAMES[$i]}"
    key="${TAG_KEYS[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done 

# rules
hc unrule -F
#hc rule class=XTerm tag=3 # move all xterms to tag 3
hc rule focus=off # normally do not focus new clients
# give focus to most common terminals
#hc rule class~'(.*[Rr]xvt.*|.*[Tt]erm|Konsole)' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK)' manage=off

# unlock, just to be sure
hc unlock

herbstclient set tree_style '╾│ ├└╼─┐'

# do multi monitor setup here, e.g.:
# hc set_monitors 1280x1024+0+0 1280x1024+1280+0
# or simply:
# hc detect_monitors

# find the panel
panel=~/.config/herbstluftwm/panel.sh
killall dzen2

[ -x "$panel" ] || panel=/etc/xdg/herbstluftwm/panel.sh
for monitor in $(herbstclient list_monitors | cut -d: -f1) ; do
    # start it on each monitor
    $panel $monitor &
done
